export enum Company {
  Apple = 'Apple',
  Google = 'Google',
  Microsoft = 'Microsoft',
  Meta = 'Meta',
  Amazon = 'Amazon',
  Netflix = 'Netflix',
  Twitter = 'Twitter',
  LinkedIn = 'LinkedIn',
  Uber = 'Uber',
  Airbnb = 'Airbnb',
  Dropbox = 'Dropbox',
  WTW = 'WTW',
  FinancialTimes = 'Financial Times',
  Other = 'Other',
}
